### ISSUE TITLE
seed in generate-images has a different behavior than in generate latent-walk

### ISSUE THREAD

**Issue by ysig** [dvschultz/stylegan2-ada#10]
Hi, 

I have been using your repo to create latent-walks.

Although for generate-images a get for seeds 1 - 1000 a very diverse set of images, if I do the same with generate latent-walk (either z or w) I seem to constantly get really small perturbations of the same picture. This happens even with latent walks, when I increase the diameter to 400.

Am I doing something wrong, or is there something wrong with your implementation?
Thank you

**Comment by dvschultz** [comment]
hmmmm...are you setting the same truncation value for both?

**Comment by ysig** [comment]
I use seed 0.5, which is the default seed.

Στις Τρί, 24 Νοε 2020 στις 1:35 π.μ., ο/η Derrick Schultz <
notifications@github.com> έγραψε:

**Comment by dvschultz** [comment]
I dug into this more last night and my guess is that to have fluid interpolations you need to fix the noise variables, which you don’t need to do with just images. I added a new flag to the `generate-images` command called `--fixnoise`. Using this will create accurate images for use in interpolations. Unfortunately there’s no way to take an exact generated seed that doesn’t use fixed noise and put it in an interpolation without introducing a lot of fine grain noise into the interpolation.

I’m going to close this for now, unless you have other suggestions.
