### ISSUE TITLE
Open question about syncing interpolation speed to music

### ISSUE THREAD

**Issue by TMorville** [dvschultz/stylegan2-ada#12]
I read your [reddit post](https://www.reddit.com/r/MachineLearning/comments/jpnpm3/p_ai_intimacy_stylegan2ada_music_video/gbfz0xu/) and I was wondering if you would share how you matched the interpolation speed to your music input? 

> The interpolation speed was driven with the kick drum (kick drum amplitude controlled the frame rate of interpolation) + the baseline of 30fps. The pad synth controls truncation value (same idea, via amplitude, but only variation between [0.8-1].

It seems to me that its dynamic? E.g. changes speed over time. But perhaps thats not the case?

**Comment by dvschultz** [comment]
this isn't me. please contact the author of that post for more information.
