### ISSUE TITLE
Generate:train  afhqcat and use model to generate images

### ISSUE THREAD

**Issue by aisdn** [dvschultz/stylegan2-ada#20]
> generate.py
Hi, I am  a senior from the department of Social Sport in a university.     
              
I have finished to train afhqcat.pkl model with relative datasets, but when I want to generate images, I would not to find this generate command examples in generate.py liking  MetFaces, CIFAR-10 and so on. 

Is there any good way for me in this situation？thanks for your great project.

**Comment by zncook** [comment]
Choice add_parser
