### ISSUE TITLE
AssertionError - What am I doing wrong?

### ISSUE THREAD

**Issue by ghost** [dvschultz/stylegan2-ada#22]
What am I doing wrong?

I loaded 1000 images from the internet, used AI to detect all the birds in them and draw a frame. Then I used AI to keep only the content of the frame. Finally I adjusted everything to 1024x1024.
Run your scripts dataset-tools.py / dedupe.py and give the output folder in your Stylegan2-Ada Colab (https://github.com/dvschultz/ml-art-colabs/blob/master/Stylegan2_ada_Custom_Training.ipynb) to train.

When executing always comes this error: 
 
!python dataset_tool.py create_from_images ./datasets/{dataset_name} {dataset_path} 

/content/googledrive/MyDrive/AI/stylegan2-ada
Loading images from "/content/googledrive/MyDrive/input/Birds1024"
Creating dataset "./datasets/Birds1024"
Added 80 images.
Traceback (most recent call last):
  File "dataset_tool.py", line 1249, in <module>
    execute_cmdline(sys.argv)
  File "dataset_tool.py", line 1244, in execute_cmdline
    func(**vars(args))
  File "dataset_tool.py", line 715, in create_from_images
    tfr.add_image(img)
  File "dataset_tool.py", line 89, in add_image
    assert img.shape == self.shape
AssertionError

I am not a programmer and do not understand what it is trying to tell me?

**Comment by dvschultz** [comment]
at least one of the images in your dataset isn’t square. `assert img.shape == self.shape` says one side length doesn’t match the other.
